#!/bin/zsh
# $ProjectHeader: volitve 0.25 Tue, 04 Nov 1997 19:56:32 +0100 andrej $ 
#
# $Id: start 1.4 Sun, 19 Oct 1997 17:07:54 +0000 andrej $ 
# Pomo¾ni skript za zagon.
cd Manager; ./manager 2> ../Log/volitve.log &; cd ..
../apache_1.2.4/bin/restart
